gsr/urls.py
from django.urls import path

from gsr import views

app_name = 'gsr'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.user_signup, name = 'signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('add_shop/', views.add_shop, name='add_shop'),
    path('add_category/', views.add_category, name='add_category'),
    path('user/', views.user, name = 'user'),
    path('search/', views.search, name='search'),
    path('shop/<slug:shop_name_slug>/', views.view_shop, name ='view_shop'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('shop/<slug:shop_name_slug>/edit_shop', views.edit_shop, name ='edit_shop'),
    path('shop/<slug:shop_name_slug>/add_review', views.add_review, name='add_review'),
    path('shop/<slug:shop_name_slug>/edit_review/<int:review_id>', views.edit_review, name='edit_review'),
    path('shop/<slug:shop_name_slug>/delete_review/<int:review_id>', views.delete_review, name='delete_review'),
    path('shop/<slug:shop_name_slug>/create_reply/', views.create_reply, name='create_reply'),
    path('shop/<slug:shop_name_slug>/show_replies/', views.show_replies, name='show_replies'),
    path('edit_user/', views.edit_user, name='edit_user'),
    path('owner_request/', views.owner_request, name='owner_request'),
]

wad_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static


from gsr import views

urlpatterns = [
    path('', views.index),
    path('gsr/', include('gsr.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gsr/forms.py
from io import BytesIO
from django import forms
from django.contrib.auth.models import User
from PIL import Image

from gsr.models import Category, OwnerGroupRequest, Shop, Review, ReviewReply


class CategoryForm(forms.ModelForm):
    """A form to create a new category"""

    class Meta:
        model = Category
        fields = ('name', 'description', 'picture')
        widgets = {
            "name" : forms.TextInput(attrs={
                "class" : "gsr-cream"
                }),
            "description" : forms.Textarea(attrs={
                'rows': '5',
                'cols': '100', 
                'class':'gsr-cream', 
                'style':'resize:none;width:90%;', 
                }),
        }


class ShopForm(forms.ModelForm):
    """A form to create a new shop"""
    
    # Override to only select users in owner group
    # owners = forms.ModelMultipleChoiceField(User.objects.filter(groups__name='Shop Owner'))
    
    def clean(self):
        # Resize picture to square
        picture = self.cleaned_data.get('picture')
        if picture:
            image = Image.open(BytesIO(picture.read()))
            image = image.resize((256, 256), Image.ANTIALIAS)
            new_image = BytesIO()
            image.save(new_image, 'PNG')
            picture.file = new_image

        return self.cleaned_data

    
    class Meta:
        model = Shop
        fields = ('name', 'description', 'picture', 'opening_hours', 'location', 'categories')
        
        widgets = {
            "picture" : forms.ClearableFileInput(attrs={
                "id" : "image_field",
                "class" : "gsr-cream  border gsr-border",
                'style':'width:90%;',
                }),
            "categories" : forms.CheckboxSelectMultiple(attrs={
                "id" : "categories",
                "class" : "list-unstyled",
                }),
            "description" : forms.Textarea(attrs={
                'rows': '5',
                'cols': '100', 
                'class':'gsr-cream', 
                'style':'resize:none;width:90%;', 
                }),
            "name" : forms.TextInput(attrs={
                "class" : "gsr-cream"
                }),
            "location" : forms.HiddenInput(attrs={
                'id' : 'location',
                }),
            "opening_hours" : forms.Textarea(attrs={
                'rows': '5',
                'cols': '100', 
                'class':'gsr-cream', 
                'style':'resize:none;width:90%;', 
                }),
                
        }
        
    def __init__(self,*args,**kwargs):
        super (ShopForm,self ).__init__(*args,**kwargs)
        self.fields['categories'].queryset = Category.objects.filter(is_approved=True)



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('customer_interaction_rating','price_rating','quality_rating','comment')

        widgets = {
            "comment": forms.Textarea(attrs={
                "style":'height:300px;',
            })
        }


class OwnerGroupRequestForm(forms.ModelForm):
    class Meta:
        model = OwnerGroupRequest
        fields = ('request_comment', 'evidence_file')
        help_texts = {
            'request_comment' : "Please describe why you would like the shop owner permissions.",
            'evidence_file' : "Please upload some evidence, such as a photo or pdf with more information.",
        }

gsr/views.py
from django.db import IntegrityError
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from gsr.models import Category, OwnerGroupRequest, RatedModel, Shop, Review, ReviewReply
from gsr.forms import CategoryForm, OwnerGroupRequestForm, ShopForm, UserForm, ReviewForm
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.http import JsonResponse

# Create your views here.

def user_signup(request):
    """TODO: Need to change the groups input probably to a boolean of is shop owner
    or not shop owner"""
    registered = False
    if request.user.is_authenticated:
        return redirect(reverse('gsr:index'))
    elif request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()

    if registered:
        return redirect(reverse('gsr:login') + "?reason=Account_Created")
    else:
        return render(request, 'gsr/signup.html', context={'user_form': user_form, 'registered': registered})


def user_login(request):
    
    if request.method == 'GET':
        reason = request.GET.get("reason")
        messages = {
            "No_Role_On_Add" : "You can't add a shop without an owner account",
            "No_Role_On_Edit": "You can't edit a shop without an owner account",
            "Unowned_Shop"   : "You can't edit a shop you don't own",
            "Unowned_Review" : "You can't edit a review you didn't write",
            "Account_Created": "Please login to your new account",
        }
        error = messages.get(reason, "")        
    elif request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:

                login(request, user)
                dest = request.POST.get('next')
                if dest is None or dest == "":
                    dest = reverse('gsr:index')
                return redirect(dest)
            else:
                return render(request, 'gsr/login.html', context={"error": "Your account is disabled"})
        else:
            return render(request, 'gsr/login.html', context={"error": "Invalid login details"})
    
    return render(request, 'gsr/login.html', context={"error" : error})


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('gsr:index'))

@login_required
def delete_account(request):
    user = request.user
    user.delete()
    logout(request)
    return redirect(reverse('gsr:index'))

@login_required
def add_shop(request):
    if not request.user.has_perm('gsr.manage_shops'):
        return redirect(reverse("gsr:login")+"?reason=No_Role_On_Add")
    
    form = ShopForm()
    context_dict = {}
    
    if request.method == 'POST':
        form = ShopForm(request.POST, request.FILES)
        
        
        if form.is_valid():
            shop = form.save(commit=True)
            shop.owners.set([request.user])
            shop.save()
            return redirect('/gsr/')
        else:
            print(form.errors)
    
    context_dict['picture'] = Shop.DEFAULT_PICTURE
    context_dict['form'] = form
    context_dict['title'] = "Add Your Shop"
    context_dict['submit_text'] = "Create Shop"
    
    return render(request, 'gsr/add_shop.html', context = context_dict)


@login_required
def add_category(request):
    if not request.user.has_perm('gsr.manage_shops'):
        return redirect(reverse("gsr:login")+"?reason=No_Role_On_Add")
    
    form = CategoryForm()
    context_dict = {}
    
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        
        
        if form.is_valid():
            category = form.save(commit=True)
            return redirect('/gsr/')
        else:
            print(form.errors)
    
    context_dict['form'] = form
    context_dict['action'] = reverse("gsr:add_category")
    context_dict['title'] = "Request a new Category"
    context_dict['submit_text'] = "Send for approval"
    
    return render(request, 'gsr/add_category.html', context = context_dict)

def update_recently_visited(request: HttpRequest, response: HttpResponse, shop: Shop):
    """Updates the user's recently visited shop list"""

    # Read cookie
    raw = request.COOKIES.get('recently_visited')
    if raw is not None and len(raw) > 0:
        names = raw.split(':')
    else:
        names = []

    # Update recently visited
    if shop.slug in names:
        names.remove(shop.slug)
    names.insert(0, shop.slug)
    names = names[:10]

    # Write cookie
    response.set_cookie('recently_visited', ':'.join(names))


def view_shop(request,shop_name_slug):
    context_dict = {}


    try:
        shop = Shop.objects.get(slug=shop_name_slug)
        reviews = Review.objects.filter(shop=shop)
        categories = [category.name for category in shop.categories.all()]

        context_dict['shop'] = shop
        context_dict['reviews'] = reviews
        context_dict['categories'] = categories
        context_dict['is_owner'] = request.user in shop.owners.all()

    except Shop.DoesNotExist:
        shop = None
        context_dict['shop'] = None
        context_dict['reviews'] = None
        context_dict['categories'] = None
        context_dict['is_owner'] = False

    response = render(request,'gsr/view_shop.html',context = context_dict)
    
    if shop is not None:
        update_recently_visited(request, response, shop)
    
    return response

@login_required
def edit_shop(request,shop_name_slug):
    if not request.user.has_perm('gsr.manage_shops'):
        return redirect(reverse("gsr:login")+"?reason=No_Role_On_Edit")
    
    context_dict = {}
    context_dict['picture'] = Shop.DEFAULT_PICTURE
    shop = get_object_or_404(Shop, slug=shop_name_slug)
    
    if request.user not in shop.owners.all() and not request.user.is_superuser: 
        return redirect(reverse("gsr:login")+"?reason=Unowned_Shop")
    
    categories = [category.name for category in shop.categories.all()]
    
    context_dict['shop'] = shop
    context_dict['categories'] = categories
    if shop.picture:
        context_dict['picture'] = shop.picture.url
        
    
    form = ShopForm(instance=shop)

    if request.method == 'POST':
        form = ShopForm(request.POST, request.FILES, instance=shop)
        
        if form.is_valid():
            shop = form.save(commit=True)
            return redirect(reverse("gsr:view_shop", args=[shop.slug] ))
        else:
            print(form.errors)
    
    context_dict['form'] = form
    context_dict['editing'] = True
    context_dict['title'] = "Edit \"" + shop.name + "\""
    context_dict['submit_text'] = "Save Changes"
    
    return render(request,'gsr/add_shop.html', context = context_dict)


def index(request):
    shoplistbyadddate = Shop.objects.order_by('-date_added')
    shoplistbystars = [
        shop
        for shop in Shop.objects.all()
    ]
    shoplistbystars.sort(key=lambda s: -s.get_rating(RatedModel.OVERALL_RATING))

    ##raw cookies
    raw = request.COOKIES.get('recently_visited')
    if raw is not None and len(raw) > 0:
        names = raw.split(':')
    else:
        names = []
    # Query the database to get the Shop objects based on the slugs in the 'names' list
    shops_queryset = Shop.objects.filter(slug__in=names)

    # Create a dictionary with the slugs as keys and the Shop objects as values
    slug_to_shop = {shop.slug: shop for shop in shops_queryset}

    # Iterate through the 'names' list and create a new list of Shop objects
    ordered_shops_recently_visited = [slug_to_shop[slug] for slug in names if slug in slug_to_shop]

    SHOP_COUNT = 10
    context = {
        'shoplistbystars':shoplistbystars[:SHOP_COUNT],
        'shoplistbyadddate':shoplistbyadddate[:SHOP_COUNT],
        'shops_recently_visited':ordered_shops_recently_visited[:SHOP_COUNT],
    }

    return render(request, 'gsr/home.html', context)

@login_required
def user(request):
    thisUser = request.user
    shops = Shop.objects.filter(owners=thisUser)
    reviews = Review.objects.filter(author=thisUser)

    has_owner_group = thisUser.groups.filter(name="Shop Owner").exists()
    requested_owner_group = OwnerGroupRequest.objects.filter(user=thisUser).exists()

    return render(
        request,
        'gsr/user.html',
        {
            'user': thisUser,
            'reviews': reviews,
            'shops': shops,
            'has_owner_group': has_owner_group,
            'requested_owner_group': requested_owner_group,
        }
    )

def search(request: HttpRequest):
    # GET parameter names
    SEARCH_QUERY_PARAM = 'query'
    SEARCH_CATEGORY_PARAM = 'category'
    SEARCH_RATING_PARAM = 'rating'

    # Special category name for no filtering
    ANY_CATEGORY = 'Any'

    # GET parameter defaults
    default_category = ANY_CATEGORY
    default_rating_method = RatedModel.OVERALL_RATING

    # Get GET parameters from request url
    query = request.GET.get(SEARCH_QUERY_PARAM)
    rating_method = request.GET.get(SEARCH_RATING_PARAM, default_rating_method)
    category_name = request.GET.get(SEARCH_CATEGORY_PARAM, default_category)
    if category_name == ANY_CATEGORY:
        category_name = None
    
    category = None
    if category_name is not None:
        filtered = Category.objects.filter(name=category_name, is_approved=True)
        if filtered:
            category = filtered[0]

    # Filter shops by category and query, sort in descending order of rating

templates/gsr/add_review.html
{% extends 'gsr/base.html' %}
{% load staticfiles %}
{% load gsr_template_tags %}

{% block title_block %}
    {% if editing %}
    Edit Review
    {% else %}
    Add Review
    {% endif %}
{% endblock %}

{% block head_block %}
    <link href="{% static 'css/gsr/common.css' %}" rel="stylesheet" crossorigin="anonymous">
{% endblock %}

{% block body_block %}

 <div class = "container-fluid mt-5"></div>
    <div class="row">
        <div class="col-md-4"></div>
        <div class="gsr-cream text-center card p-2 col-md-3">
            {% if editing %}
            <h1>Edit review</h1>
            {% else %}
            <h1>Write a review</h1>
            {% endif %}
        </div>
    </div>
    <br />
    {% if editing %}
    <form id="review_form" method="post" action="{% url 'gsr:edit_review' shop.slug review.id %}">
    {% else %}
    <form id="review_form" method="post" action="{% url 'gsr:add_review' shop.slug %}">
    {% endif %}
            {% csrf_token %}
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-2">
                <h5>{{ form.customer_interaction_rating.label_tag }}</h5>
            </div>
            <div class="col-md-1">
                {{ form.customer_interaction_rating }}
            </div>
        </div>

        <br/>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-2">
                <h5>{{ form.quality_rating.label_tag }}</h5>
            </div>
            <div class="col-md-1">
                {{ form.quality_rating }}
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-2">
                <h5>{{ form.price_rating.label_tag }}</h5>
            </div>
            <div class="col-md-1">
                {{ form.price_rating }}
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-5"></div>
            <div class="col-md-2">
                <h5>{{ form.comment.label_tag }}</h5>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-3">
                <h5>{{ form.comment|add_class:"form-control" }}</h5>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6"></div>
            <div class="col-md-1">
                <input type="submit" value="Submit" class="form-control gsr-cream" />
            </div>
        </div>

    </form>

{% endblock %}

templates/gsr/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head lang="en">
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">

		{# Import common, jquery and js-cookie js #}
		<script src="{% static 'js/jquery/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
		<script src="{% static 'js/gsr/common.js' %}" crossorigin="anonymous"></script>

		{# Import common, bootstrap and font-awesome css #}
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
		<link href="{% static 'css/gsr/common.css' %}" rel="stylesheet" crossorigin="anonymous">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" crossorigin="anonymous">
		
		{# Allow templates to change page title #}
		<title>Glasgow Shop Ratings - 
		{% block title_block %}
			Base title
		{% endblock %}
		</title>

		{# Allow templates to add extra head tags #}
		{% block head_block %}
		{% endblock %}

	</head>

    <body>
		{# Header bar #}
		<nav class="navbar navbar-expand-sm bg-dark navbar-dark navbar-custom">
			<div class="container-fluid">
				<a class="navbar-brand" href="{% url 'gsr:index' %}">Glasgow Shop Ratings</a>
				
				<form id="search-form" class="d-flex" action="{% url 'gsr:search' %}" method="GET">
					<input class="form-control me-2" type="text" placeholder="Search Shops" id="query" name="query">
					<button class="btn btn-primary" type="submit">Search</button>
				</form>
				
				<ul class="navbar-nav">
					{% if user.is_authenticated %}
						<li class="nav-item">
							<button class="nav-link gsr-nav-button ms-3" onclick="window.location.href='{% url 'gsr:user' %}'"> Profile - {{ user.username }}</button>
						</li>	
						<li class="nav-item">
							<button class="nav-link gsr-nav-button ms-3" onclick="window.location.href='{% url 'gsr:logout' %}'">Logout</button>
						</li>
					{% else %}
						<li class="nav-item">
							<button class="nav-link gsr-nav-button ms-3" onclick="window.location.href='{% url 'gsr:login' %}'">Login</button>
						</li>
						<li class="nav-item">
							<button class="nav-link gsr-nav-button ms-3" onclick="window.location.href='{% url 'gsr:signup' %}'">Signup</button>
						</li>
					{% endif %}
				</ul>
			</div>
		</nav>

		{# Page specific content #}
		<div>
		{% block body_block %}
			<!-- This is body_block's default content. -->
		{% endblock %}
		</div>

		{# Import bootstrap js (apparently a performance boost to put this at the end) #}
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
	</body>
</html>

templates/gsr/owner_request.html
{% extends 'gsr/base.html' %}
{% load staticfiles %}
{% load gsr_template_tags %}

{% block title_block %}
Owner Group Request
{% endblock %}

{% block body_block %}

<div class="container my-3 border gsr-border gsr-blue">
    <div class="row">
        <h3>Owner Group Request</h3>
    </div>
    <div class="row">
        <p>The owner group allows you to add your shops to the website.</p>
        <p>Please provide some evidence of identity and ownership if you would like to apply.</p>
    </div>
</div>

<div class="container my-3">
    <div class="row border gsr-border gsr-cream">
        <form class="my-3" action="{% url 'gsr:owner_request' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
                <h4>{{ field.label }}</h4>
                <p>{{ field.help_text }}</p>
                {{ field }}
            </div>
            {% endfor %}
            <div>
                <input type="submit" value="Submit">
            </div>
        </form>
        {{ form.errors }}
    </div>
</div>

{% endblock %}

templates/gsr/sign_up.html
{% extends 'gsr/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Sign Up
{% endblock %}

{% block body_block %}

{% if registered %}
    <strong>Your ready to go</strong>
    <a href="{% url 'gsr:index' %}">Home</a>
{% else %}
    <h1>create an account</h1>
    <form id="user_form" method="post" action="{% url 'gsr:sign_up' %}">
        {% csrf_token %}
        {{ user_form.as_p }}
        <input type="submit" name="sign_up" value="sign Up" />
    </form>
{% endif %}
{% endblock %}

templates/gsr/user.html
{% extends 'gsr/base.html' %}
{% load staticfiles %}
{% load gsr_template_tags %}

{% block title_block %}
Profile
{% endblock %}

{% block head_block %}
<script src="{% static 'js/gsr/user.js' %}" crossorigin="anonymous"></script>
{% endblock %}

{% block body_block %}

<div class="delbutton">
    {% if has_owner_group %}
    <button id="createshopbtn" onclick="window.location.href='{% url 'gsr:add_shop' %}'"
        style="background-color:yellow;margin-top:0px;padding: 10px;margin-right:40px;width:8%;height:100%;float:right">Create
        Shop</button> </p>
    {% elif requested_owner_group %}
    <button disabled
        style="background-color:yellow;margin-top:0px;padding: 10px;margin-right:40px;width:8%;height:100%;float:right">
        Shop Owner Group has been requested</button> </p>
    {% else %}
    <button onclick="window.location.href='{% url 'gsr:owner_request' %}'"
        style="background-color:yellow;margin-top:0px;padding: 10px;margin-right:40px;width:8%;height:100%;float:right">
        Request Shop Owner Group</button> </p>
    {% endif %}

</div>
<div class="container">
    <p id="usernamebox"
        style="display:inline-block ;background-color: white;margin-top:50px;margin-left:30px;width:40%;height:100%;">
        Username: <span id="usernametext">{{ user.username }}</span> <span id="usernametext-updating"><i>Updating...</i></span> </p>
    <button id="editusernamebtn"
        style="display:inline-block ;background-color:yellow;margin-top:0px;margin-left:0px;width:8%;height:100%;">Edit</button>
    <input id="usernamebox-edit"
        style="display:inline-block ;background-color: white;margin-top:50px;margin-left:30px;width:40%;height:100%;">
    <button id="saveusernamebtn"
        style="display:inline-block ;background-color:yellow;margin-top:0px;margin-left:0px;width:8%;height:100%;">Save</button>
</div>
<div class="container">
    <p id="emailbox"
        style="display:inline-block ;background-color: white;margin-top:0px;margin-left:30px;width:40%;height:100%;">
        Email: <span id="emailtext">{{ user.email }}</span> <span id="emailtext-updating"><i>Updating...</i></span> </p>
    <input id="emailbox-edit"
        style="display:inline-block ;background-color: white;margin-top:50px;margin-left:30px;width:40%;height:100%;">
    <button id="editemailbtn"
        style="display:inline-block ;background-color:yellow;margin-top:0px;margin-left:0px;width:8%;height:100%">Edit</button>
    <button id="saveemailbtn"
        style="display:inline-block ;background-color:yellow;margin-top:0px;margin-left:0px;width:8%;height:100%">Save</button>
</div>
<div class="delbutton">
    <button onclick="window.location.href='{% url 'gsr:delete_account' %}'"
        style="background-color:red;margin-top:20px;margin-left:100px;width:20%">DELETE ACCOUNT</button>
</div>

<div class="container">
    <p class="revieworshops"></p>
    <button id="reviewsbtn"
        style="display:inline-block ;background-color:rgb(240, 240, 64);margin-top:0px;margin-left:80px;width:20%;height:100%">Your
        Reviews</button>
    <button id="shopsbtn"
        style="display:inline-block ;background-color:rgb(240, 240, 64);margin-top:0px;margin-left:0px;width:20%;height:100%">Your
        Shops</button>
</div>

<div class="container" id="Reviewsid" style="margin-top: 40px; width: 90%;border: 1px solid black;background: white;">
    <h3>Your Reviews</h3>
    <div class="reviews-container" style="overflow-y: scroll; max-height: 300px; border: 1px solid black; margin-bottom: 20px;">
        {% for review in reviews%}
        <div class="container"style="margin-top: 10px; margin-bottom: 0px;">
            <p class="shopname"
                style="display:inline-block;background-color: white;margin-top:0px;margin-left:0px;width:75%;height:100%;border: 1px solid black;">
                <a href="{% url 'gsr:view_shop' review.shop.slug %}">{{ review.shop }}</a>
            </p>
            <p class="rating"
                style="display:inline-block;background-color: white;margin-top:0px;margin-left:0px;width:10%;height:100%;border: 1px solid black;">
                Rating</p>
            <p class="stars"
                style="display:inline-block;background-color: white;margin-top:0px;margin-left:0px;width:10%;height:100%;border: 1px solid black;">
                {% star_rating review "Overall Rating" %}</p>

        </div>
        <div class="container">
            <div class="commentbox"
                style="display:inline-block ;background-color: white;margin-top:0px;margin-left:0px;width:95.5%;;min-height: 100px;border: 1px solid black;">
                {{ review.comment|linebreaks }} </div>
            <button id="editreview" onclick="window.location.href='{% url 'gsr:edit_review' review.shop.slug review.id %}'"
            style="display:inline-block ;background-color:yellow;margin-top:0px;margin-left:0px;margin-bottom: 10px;width:10%;">
                Edit</button>
        </div>
        {% empty %}
        <p>You haven't left any reviews yet.</p>
        {% endfor %}
    </div>
</div>

<div class="container" id="Shopsid" style="margin-top: 40px; width: 90%;border: 1px solid black;background: white; display: none">
    <h3>Your Shops</h3>
    <div class="shops-container" style="overflow-y: scroll; max-height: 300px; border: 1px solid black; margin-bottom: 20px;">
        {% for shop in shops %}
        <div class="container" style="margin-top: 10px; margin-bottom: 0px;">
            <p class="shopname"
                style="display:inline-block ;background-color: white;margin-top:0px;margin-left:0px;width:75%;height:100%;border: 1px solid black;">
                <a href="{% url 'gsr:view_shop' shop.slug %}">{{ shop.name }}</a>
            </p>
            <p class="rating"
                style="display:inline-block ;background-color: white;margin-top:0px;margin-left:0px;width:10%;height:100%;border: 1px solid black;">
                Rating</p>
            <p class="stars"
                style="display:inline-block ;background-color: white;margin-top:0px;margin-left:0px;width:10%;height:100%;border: 1px solid black;">
                {% star_rating shop "Overall Rating" %}</p>

        </div>
        <div class="container">
            <div class="descriptionbox"
                style="display:inline-block ;background-color: white;margin-top:0px;margin-left:0px;width:95.5%;;min-height: 100px;border: 1px solid black;">
                {{ shop.description|linebreaks }} </div>
                <button id="editshop" onclick="window.location.href='{{ shop.get_edit_url}}'"
                style="display:inline-block ;background-color:yellow;margin-top:0px;margin-left:0px;margin-bottom: 10px;width:10%;">
                Edit</button>
            
        </div>
        {% empty %}
        <p>You don't own any shops yet.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}